---
#
# aasf-infra-auto/roles/central-deploy/tasks/cen-component-install.yml
#

- name: create user for AASF Central Node component
  user:
    name={{ component }}
    group={{ cen_user_grp }}
    home={{ cen_home_dir }}/{{ component }}
    createhome=yes
    state=present
    shell=/bin/bash

- name: move files for AASF Central Node components into place
  shell: mv {{ cen_home_dir }}/aasf/{{ component }}/* {{ cen_home_dir }}/{{ component }}/
  args:
    chdir={{ cen_home_dir }}

- name: ensure conf directory is present for each AASF Node0 component
  file:
    path={{ cen_home_dir }}/{{ component }}/conf
    state=directory
    recurse=yes
    owner={{ component }}
    group={{ cen_user_grp }}
    mode=0770
    
- name: move templates for AASF Central Node components into place
  template:
    backup=yes
    dest={{ cen_home_dir }}/{{ component }}/conf/{{ item | basename | regex_replace('\.j2','') }}
    group={{ cen_user_grp }}
    mode={{ 0660 }}
    owner={{ component }}
    src={{ item }}
  with_fileglob:
    - ../templates/{{ component }}/*.j2
  ignore_errors: yes

- name: create log directories for AASF Central Node components
  file:
    state=directory
    path=/var/log/{{ component }}
    owner={{ component }}
    group={{ cen_user_grp }}
    mode=0775

- name: include component-specific scripts for AASF Central Node components
  include: "{{ component }}.yml"
