#
# mesos-cluster/roles/kafka/tasks/kafka-firewalld-rules.yml
#

 - name: setup Kafka firewalld rules
   firewalld: port={{ item }}/tcp permanent=yes state=enabled immediate=yes
   with_items: 
     - 9092

