---
#
# aasf-infra-auto/roles/remote-deploy/tasks/csfms.yml
#
- name: create extract  directory
  file: dest=/opt/aasf/csfms/csf-sdk-0.0.1-SNAPSHOT state=directory owner=root group=root

- unarchive:
    src: /opt/aasf/csfms/lib/csf-sdk-0.0.1-SNAPSHOT.jar
    dest: /opt/aasf/csfms/csf-sdk-0.0.1-SNAPSHOT
    copy: no
    remote_src: yes

- lineinfile:
    dest: /opt/aasf/csfms/csf-sdk-0.0.1-SNAPSHOT/log4j2.xml
    regexp: \$\{sys\:bulkbootstrapServers\}
    line: <Property name="bootstrap.servers">localhost:9092</Property>

- name: mv lib
  command: mv /opt/aasf/csfms/lib/csf-sdk-0.0.1-SNAPSHOT.jar /opt/aasf/csfms/lib/csf-sdk-0.0.1-SNAPSHOT.jar.bck  

- name: pack it back to lib
  shell: tar cvf csf-sdk-0.0.1-SNAPSHOT.jar /opt/aasf/csfms/csf-sdk-0.0.1-SNAPSHOT  chdir=/opt/aasf/csfms/lib/

- file: path=/opt/aasf/csfms/csf-sdk-0.0.1-SNAPSHOT state=absent
- file: path=/opt/aasf/csfms/csf-sdk-0.0.1-SNAPSHOT state=directory
# no start scripts here yet for csfms component
