---
#
# aasf-infra-auto/roles/remote-deploy/tasks/main.yml
#

# Thoughts:
#   add switch to deploy code from local versus online repo
#   add switch to push artifacts from ansible node or pull from online
#     repo on the remote node


- name: run deployment when rem_deploy_mode is set to install
  include: rem-install.yml
  when: rem_deploy_mode == "install"

- name: remove deployment when rem_deploy_mode is set to remove
  include: rem-remove.yml
  when: rem_deploy_mode == "remove"
