---
#
# aasf-infra-auto/roles/remote-deploy/tasks/rem-component-install.yml
#

#- set_fact: component="{{ item }}"

- name: create user for component
  user:
    name={{ component }}
    group={{ rem_user_grp }}
    home={{ rem_home_dir }}/{{ component }}
    createhome=yes
    state=present
    shell=/bin/bash

- name: move files for AASF components into place
  shell: mv {{ rem_home_dir }}/aasf/{{ component }}/* {{ rem_home_dir }}/{{ component }}/
  args:
    chdir={{ rem_home_dir }}

- name: move templates for components into place
  template:
    backup=yes
    dest={{ rem_home_dir }}/{{ component }}/conf/{{ item | basename | regex_replace('\.j2','') }}
    group={{ rem_user_grp }}
    mode={{ 0660 }}
    owner={{ component }}
    src={{ item }}
  with_fileglob:
    - ../templates/{{ component }}/*.j2
  ignore_errors: yes

- name: create log directories for AASF components
  file:
    state=directory
    path=/var/log/{{ component }}
    owner={{ component }}
    group={{ rem_user_grp }}
    mode=0775

- name: include component-specific scripts for AASF components
  include: "{{ component }}.yml"
  
