rem_server_broker_id: "0"
rem_server_listeners: "PLAINTEXT://AASF_KAFKA_LISTENER_HOST:AASF_KAFKA_LISTENER_PORT"
rem_server_port: "AASF_KAFKA_LISTENER_PORT"
rem_server_host_name: "AASF_KAFKA_LISTENER_HOST"
rem_server_num_network_threads: "3"
rem_server_num_io_threads: "8"
rem_server_socket_send_buffer_bytes: "102400"
rem_server_socket_receive_buffer_bytes: "102400"
rem_server_socket_request_max_bytes: "104857600"
rem_server_log_dirs: "/tmp/kafka-logs"
rem_server_num_partitions: "1"
rem_server_num_recovery_threads_per_data_dir: "1"
rem_server_log_retention_hours: "168"
rem_server_log_segment_bytes: "1073741824"
rem_server_log_retention_check_interval_ms: "300000"
rem_server_zookeeper_connect: "AASF_ZOOKEEPER"
rem_server_zookeeper_connection_timeout_ms: "6000"
