rem_csf_controlproxy_csf_controller_control_topic_in: "control-topic-in"
rem_csf_controlproxy_csf_controller_control_topic_out: "control-topic-out"
rem_csf_controlproxy_csf_controlproxy_node_id: "AASF_NODE_ID"
rem_csf_controlproxy_csf_controlproxy_control_topic_in: "control-topic-in"
rem_csf_controlproxy_csf_controlproxy_control_topic_out: "control-topic-out"
rem_csf_controlproxy_bootstrap_servers: "AASF_KAFKA_LISTENER_HOST:AASF_KAFKA_LISTENER_PORT"
rem_csf_controlproxy_zookeeper_connect: "localhost:2181/kafka"
rem_csf_controlproxy_acks: "all"
rem_csf_controlproxy_retries: "0"
rem_csf_controlproxy_batch_size: "16384"
rem_csf_controlproxy_linger_ms: "1"
rem_csf_controlproxy_buffer_memory: "33554432"
rem_csf_controlproxy_key_serializer: "org.apache.kafka.common.serialization.ByteArraySerializer"
rem_csf_controlproxy_value_serializer: "org.apache.kafka.common.serialization.ByteArraySerializer"
rem_csf_controlproxy_group_id: "csf-controlproxy-cg"
rem_csf_controlproxy_enable_auto_commit: "false"
rem_csf_controlproxy_auto_commit_interval_ms: "1000"
rem_csf_controlproxy_session_timeout_ms: "30000"
rem_csf_controlproxy_key_deserializer: "org.apache.kafka.common.serialization.ByteArrayDeserializer"
rem_csf_controlproxy_value_deserializer: "org.apache.kafka.common.serialization.ByteArrayDeserializer"
