---
# tasks file for zookeeper-master
#
# source = https://gitscm.cisco.com/projects/STIC/repos/ansible-roles-mesos-cluster/browse/roles/zookeeper-master/tasks/el-zookeeper-pkgs.yml?raw
#

- name: Install Zookeeper packages (EL7)
  yum:
    name={{ item }}
    state=present
  sudo: yes
  with_items:
    - java-1.7.0-openjdk-headless
    - mesosphere-zookeeper
  when: ansible_distribution_major_version >= "7"

- name: Install Cloudera repo for Zookeeper (EL6)
  yum:
    name=http://archive.cloudera.com/cdh4/one-click-install/redhat/6/x86_64/cloudera-cdh-4-0.x86_64.rpm
    state=present
  sudo: yes
  when: ansible_distribution_major_version <= "6"

- name: Install Zookeeper packages (EL6)
  yum:
    name={{ item }}
    state=present
  sudo: yes
  with_items:
    - java-1.8.0-openjdk-headless
    - zookeeper
    - zookeeper-server
  when: ansible_distribution_major_version <= "6"
