---
#
# mesos-cluster/roles/zookeeper-master/tasks/zk-iptables-rules.yml
#
# source =
#
# depends on these variables/ports:
# zk_client_port, zk_master_port, zk_election_port

- name: setup Zookeeper iptables rules
  shell: iptables -A INPUT -m state --state NEW -m tcp -p tcp --dport {{ item }} -j ACCEPT
  with_items:
    - "{{ zk_client_port }}"
    - "{{ zk_master_port }}"
    - "{{ zk_election_port }}"

- name: persist Zookeeper iptables rules
  shell: /sbin/service iptables save
